### ISSUE TITLE
Plugin seems make Postcss crash

### ISSUE THREAD

**Issue by Jerome1337** [benface/tailwindcss-children#10]
I imported and configured the plugin as the doc said.

When I run my rollup command I get an error

```bash
[!] (plugin postcss) Error: Expected an opening square bracket.
```

I use:
* Tailwind `1.2.0`
* Svelte `3.0.0`
* Rollup `1.20.0`

**Comment by benface** [comment]
@Jerome1337 Can you please share a simple repo that reproduces the issue?

**Comment by Jerome1337** [comment]
@benface You can try using this [branch](https://github.com/Los-Crackitos/meeting-room-booking/tree/tailwind-children)

**Comment by benface** [comment]
@Jerome1337 Huh, ok, that's a weird one. I've tracked it down to the `focus-within` and `children-focus-within` variants conflicting with `cssnano`'s `postcss-merge-rules` and `postcss-minify-selectors`, which both use an old version of `postcss-selector-parser` internally, which is where the error occurs as you can see from the stack trace:

```
[!] (plugin postcss) Error: Expected an opening square bracket.
src/main.pcss
Error: Expected an opening square bracket.
    at /Users/benface/Downloads/meeting-room-booking-master/front/src/main.pcss:3:1
    at Root._error (/Users/benface/Downloads/meeting-room-booking-master/front/node_modules/postcss-merge-rules/node_modules/postcss-selector-parser/dist/parser.js:137:24)
```

I don't have time to dig further right now, but an easy workaround is to disable `cssnano`'s `mergeRules` and `minifySelectors` options in your `postcss.config.js`:

```js
      cssnano({
         autoprefixer: false,
         preset: ['default', {
            mergeRules: true,
            minifySelectors: false,
         }],
      }),
```

Or, if you don't plan on using the `focus-within` or `children-focus-within` variants, you can remove those from the `display` variants array in `tailwind.config.js`.

**Comment by Jerome1337** [comment]
@benface Ok thanks for you reply, I will remove the 2 variants for now.

Let me know if there is any thing I can do to resolve the issue :)
