### ISSUE TITLE
BLACK LIVES MATTER - please read

### ISSUE THREAD

**Issue by SamGoody** [benface/tailwindcss-children#14]
Can I suggest that BLACK LIVES MATTER is not a good opener for any serious project?

Background:
I am an activist of the first level. I moved into a low-income area and have spent the past ten years providing education money, and support, trying to improve the lives, and championing the cause of those living in such areas. I adopted a kid with a police record longer than your arm, and worked with him getting detoxed. I spend most of my waking hours on this, all volunteer.

All this being destroyed by movements like BLACK LIVES MATTER.

For whatever the reason, correctly or not, that tag is associated by many with vandalism, terrorism, and destruction.  
It is a movement which claims (in the eyes of the public), "If you believe that black lives matter, you should let them burn down stores, murder people, and destroy communities. If not, you must think that black people are not important!"  
I cannot overestimate how bad that is for the people you portend to be helping.

When you add "Be angry", it projects that feeling. Which is a crying shame. When you make that the header of the project, it turns the project into a angry picket. To the detriment of everyone.

To be clear - I am VERY anti police. In my list of people to turn to for help, police usually don't show up. And the militarization and violence deserves to have them disbanded. I wish I could do something about that.

But not with a movement like this one. This will almost certainly add to strengthening the police, as the people who actually give the orders depend on the police to protect them from the rioters.  And the people who pay for their ad campaigns are in the same boat, and will certainly give them lots of money to strengthen the cops in such times.

Please, try to see how to help us, but see that it is a way that helps and is not just a vent for feelings that is actually destructive.

PS. I wish there was a way we could have a conversation about this. It is beyond frustrating for me. Students that were on track to get out of the slums, and become productive, are now all hate filled and riled up, and they may never get back on track.

**Comment by SamGoody** [comment]
I realize that my title was not clear.

I argued with a friend who was also promoting BLACK LIVES MATTER.

He said that he agrees in concept, but if the riots bring down Trump, it is worth anything. In which case it is all politics.  I made the immediate assumption that you are in the same frame of mind. 

Since that is likely not correct, I will leave this as a note of explnation, but wait to see if you respond. 

Alll the best, and please understand that I agree with your sentiments.

**Comment by benface** [comment]
Hi Sam. First of all, thank you for taking the time to write this message. I think it's important to have conversations about this. Obviously, everything is not (excuse the pun) black or white. However, I **am** 100% anti-racist. Not 99%, not "it depends", but 100%. Does that mean that I am also 100% anti-police or 100% pro-burning stores down? No. But black lives matter, and not doing anything is not gonna cut it. I disagree with your premise:

> It is a movement which claims (in the eyes of the public), "If you believe that black lives matter, you should let them burn down stores, murder people, and destroy communities. If not, you must think that black people are not important!"

That sounds like the kind of rhetoric that Trump uses. Let's work together, not against each other.

> It assumes that you know that BLACK LIVES MATTER is bad for African Americans and other minorities, but want the riots to bring down Trump.

I do not know that, and I do not think that. I hate Trump like you (probably) do and would love to bring him down, but this is not about that.

**Comment by SamGoody** [comment]
Unfortunately, it doesn't matter what the movements' leaders think they are saying.  
It maters what the people think they are trying to say. And most everyone I know - especially the minorities I work with - think that the message is as I said above.

Such a message is phenomenally destructive to everyone. Not just because of the negativity it generates to the blacks, and not just because it strengthens the position of the pro law enforcers.

I grew up in the Hudson River project. There was a dude some ten years older than myself - a programmer (back before computers were a thing) - who convinced me that I can do something with my life, but I have to take the onus of responsibility upon myself - even when it is someone else's fault.

That's the message I now try to give over - you guys are awesome, and some day you can change this whole here community around. But you gotta take the whole responsibility upon yourselves - especially when it is not your fault.

That's a big message, and hard for me to write in a post like this, but it works. I have hundreds of students that have healthy lives, and we have grown to 30 volunteers who help me.

When there are riots like these it passes a huge message - it is all "their" fault, and "we" deserve everything because of it, and we **don't need to take any responsibility**.

I am getting emotional as I write, which isn't good - because as I say to others, think! Think what will get you where you need to be, don't just do what your instincts tell you to do.

You can change the world for real. Take ONE black kid. Start a conversation with him. Paint a picture of how he can build whatsapp and sell out for a billion bucks. Tell him he has to learn how to delay gratification and take responsibility. (I use whatsapp because that is what the founders did). 

But don't do things if they will be detrimental, even if they feel good. And BLACK LIVES MATTER is detrimental, even though it feels good.

As an aside, unfortunately, I think Biden is even worse than Trump. Slim pickings.

**Comment by SamGoody** [comment]
Please do not take offense if you feel I wrote too strongly.  
Although obviously it is a matter I care about, I am not intending to flame or be offensive.

**Comment by bradley-varol** [comment]
I absolutely do not support this movement, the destruction it is causing or the racial divide it is creating. Putting this message on a GitHub project isn't activism and I now dislike the movement even more for yet another unnecessary attempt at forcing it on me. Good job! 👍🏻

**Comment by benface** [comment]
> Putting this message on a GitHub project isn't activism
🤔

>  I now dislike the movement even more for yet another unnecessary attempt at forcing it on me
I'm not forcing anything on anyone.

> The majority are like me and don't support BLM but most are afraid to talk about it publicly because of the cancel culture of the left
If even 1%, let alone the majority, doesn't believe that Black lives matter, there's a serious problem.

I'm not going to delete your comment; why would I? I am however going to close this issue because I don't really see the point in debating with you or anyone. This is my repo and I choose to support BLM.

**Comment by judehunter** [comment]
wow what a shit show.
@benface you are obviously right, thanks for trying to make the world a better place

**Comment by nicolebeaumont** [comment]
I just wish politics stayed out of github entirely
