### ISSUE TITLE
Add Children selectors for margins and paddings

### ISSUE THREAD

**Issue by Alessandroinfo** [benface/tailwindcss-children#8]
I think it's very useful adding children variant for margins and paddings.

**Comment by benface** [comment]
Hey thanks for your interest @Alessandroinfo. Yeah, that's mostly the reason I made this plugin :) That and borders. Did you have a feature request or is this just a comment?

**Comment by Alessandroinfo** [comment]
I tried adding children:p-5 but this don't work.

**Comment by benface** [comment]
@Alessandroinfo You need to add `children` to the list of variants for each property you want to use it with:

```js
// tailwind.config.js
{
  variants: {
    padding: ['children', 'default', 'responsive'],
  },
}
```

**Comment by Alessandroinfo** [comment]
Oh perfect, many thanks. I didn't understand how the configuration works. I recommend adding it to the documentation.

**Comment by benface** [comment]
@Alessandroinfo [It is](https://github.com/benface/tailwindcss-children#usage). Or did you mean to be more explicit about it? Maybe I could link to this page from the Tailwind CSS docs: https://tailwindcss.com/docs/configuring-variants ?

**Comment by Alessandroinfo** [comment]
Can you help me in adding children selector for bg hover?

**Comment by benface** [comment]
@Alessandroinfo That would be a different variant, `children-hover`. You need to add it to the `backgroundColor` property, like this:

```js
  variants: {
    backgroundColor: ['children', 'default', 'children-hover', 'hover', 'focus', 'responsive'],
  },
```
(assuming you also want Tailwind's default values of `hover`, `focus`, and `responsive`, as well as the standard `children` variant)

And then in your HTML:
```
<div class="children:bg-gray-200 children:hover:bg-gray-100">
    <a class="block p-2" href="#">Some button</a>
    <a class="block p-2" href="#">Some other button</a>
</div>
```

**Comment by Alessandroinfo** [comment]
> @Alessandroinfo That would be a different variant, `children-hover`. You need to add it to the `backgroundColor` property, like this:
> 
> ```js
>   variants: {
>     backgroundColor: ['children', 'default', 'children-hover', 'hover', 'focus', 'responsive'],
>   },
> ```
> 
> (assuming you also want Tailwind's default values of `hover`, `focus`, and `responsive`, as well as the standard `children` variant)
> 
> And then in your HTML:
> 
> ```
> <div class="children:bg-gray-200 children:hover:bg-gray-100">
>     <a class="block p-2" href="#">Some button</a>
>     <a class="block p-2" href="#">Some other button</a>
> </div>
> ```

Many thanks.

**Comment by benface** [comment]
You're welcome!
